# Generated by Django 4.0.7 on 2022-09-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes'),
        ),
    ]
